### ISSUE TITLE
padding change to margin

### ISSUE THREAD

**Issue by Joxa-UZ** [Shahzod001/AnsorMed#2]
Assalomu alaykum

Shahzod , site navbar qismida li taglarini orasidagi masofa margin bilan ochish tavsiya etiladi lekin padding ishlatganiz aslida xato emas ammo margin tavsiya etilgan va shuni to'g'irlab qo'ysak maqsadga muvofiq bo'lar edi.

![image](https://user-images.githubusercontent.com/105357849/175825473-76fa7cf0-593d-4785-93c2-aa5e19b87cd9.png)

**Comment by Shahzod001** [comment]
Voalekum Assalom kattakon rahmat! Sizning yordamiz bilan hatoni tog'irlab qoydim!
