### ISSUE TITLE
a href display

### ISSUE THREAD

**Issue by Joxa-UZ** [Shahzod001/AnsorMed#3]
Assalomu alaykum

Shahzod, sitening hero qismidagi a hrefda yozilgan button div ichiga to'liq joylasha olmagan ya'ni u tabiiy xolatida turibdi, agar siz shu xolatda har doim a hrefga display: inline-block; berib ketsangiz u div ichidan joylashadi. Agar biz bu xolatni o'zgaritirib qo'ysak ajoyib bo'lar edi. 

![image](https://user-images.githubusercontent.com/105357849/175825747-3d602ee0-25b4-4045-9a3e-d5e097aa5322.png)

**Comment by Shahzod001** [comment]
Kattakon rahmat! Tog'irlab qoydim!
